### ISSUE TITLE
`HandlerLike` signature doesn't match actual `server.Handler`. Missing `connInfo`

### ISSUE THREAD

**Issue by ericls** [cmorten/superdeno#41]
# `HandlerLike` signature doesn't match actual `server.Handler`. Missing `connInfo`

Setup:

- Deno Version: deno 1.20.6
- v8 Version: v8 10.0.139.6
- Typescript Version:  4.6.2
- SuperDeno Version: 4.8

## Details

The actual `server.Handler` takes a second argument called `connInfo` that contains information for the http request. See [here](https://deno.land/std@0.141.0/http/server.ts#L35) and quoted:

```typescript
export type Handler = (
  request: Request,
  connInfo: ConnInfo,
) => Response | Promise<Response>;
```

But `RequestHandlerLike` defined in this project doesn't match that. And when actually testing the handler, this project calls the handler with `return await app(request);` with the `connInfo` argument missing.

**Comment by ericls** [comment]
@asos-craigmorten , yea that sounds reasonable. I haven't looked into the other frameworks/tools this library tries to support tho.. And when testing I guess it can just pass in a fake ConnLike or make a method to allow the user to specify it? Something like: 
```typescript
superdeno(...)
  .setConn()
```
?

**Comment by ericls** [comment]
> @asos-craigmorten , yea that sounds reasonable. I haven't looked into the other frameworks/tools this library tries to support tho.. And when testing I guess it can just pass in a fake ConnLike or make a method to allow the user to specify it? Something like:
> 
> ```ts
> superdeno(...)
>   .setConn()
> ```
> 
> ?

Okay, I took a look at the code and find my previous statement doesn't make much sense and the connection info is not easy to mock in this case. Looks like we just need to fix the typing and actually pass the connInfo to the handler function in the managed server instance.

**Comment by asos-craigmorten** [comment]
Going to reopen as think this is valid, and be good to keep to track the fix/feature (depending on how see it!)

**Comment by talentlessguy** [comment]
I'm rewriting tinyhttp for native http and I faced a similar problem. The `app.handle` needs both `req` and `connInfo`
