### ISSUE TITLE
Question: How to run superdeno with plain deno server

### ISSUE THREAD

**Issue by yereby** [cmorten/superdeno#42]
Hi,

I would like to know if it is possible to run superdeno with just a plain server with `serve` from deno `http` package, and not with opine or another framework. I can't find any resource.

Thanks a lot.

**Comment by asos-craigmorten** [comment]
Hi @yereby 👋 

This should be possible - see the superdeno tests for examples --> https://github.com/cmorten/superdeno/blob/main/test/superdeno.std.test.ts

**Comment by yereby** [comment]
Ho yes ! I was just running the test with `deno run` and not `deno test`...
It works well. You can close this dummy issue :)
