### ISSUE TITLE
Can this be used with `express`?

### ISSUE THREAD

**Issue by TillaTheHun0** [cmorten/superdeno#43]
# Issue

Really a question, but with Opine being in maintenance mode, I tried the recommendation of using `express` on Deno.

I tried using `superdeno` to test routes, but when I run the test, the tests fails and then just hangs the process.

Steps to reproduce:

Run this using `deno test`:
```ts
// @deno-types="npm:@types/express@^4.17"
import express from "npm:express@4.18.2";
import { superdeno } from "https://deno.land/x/superdeno@4.8.0/mod.ts";

const app = express();

app.get("/", (_req, res) => res.json("hello express"));

Deno.test("mod", async () => {
  await superdeno(app).get("/").expect("hello express").end();
});
```

I also tried using `npm:supertest` but that doesn't seem to work with `npm:express` on Deno either 🤷 .

I guess am not sure what the expectation is (pun unintended) for testing express apps on top of deno. Should I be spinning the app up and down in tests, and then manually calling with `fetch`?

Setup:

deno 1.31.1 (release, x86_64-unknown-linux-gnu)
v8 11.0.226.13
typescript 4.9.4

SuperDeno Version: 4.8.0

## Details

Besides Opine being in maintenance mode, the hard impetus for trying out express on Deno was because my tests started to fail using `superdeno` and `opine` together. The tests seem to run, but then an error is thrown after each file is executed by Deno:

```
error: TypeError: core.runMicrotasks is not a function
    core.runMicrotasks();
         ^
    at processTicksAndRejections (https://deno.land/std@0.153.0/node/_next_tick.ts:62:10)
    at https://deno.land/std@0.153.0/node/process.ts:312:7
```

With some digging, it seems that `opine` is importing theses deps from `std`, and those deps are using an api [removed in later versions of deno](https://github.com/denoland/deno/issues/17742), which is causing an error to be thrown on `beforeunload`.

Don't know if this should be an issue on `opine`, but it seems opine cannot be used inside of `Deno.test`.

**Comment by jefripunza** [comment]
up
